### ISSUE TITLE
m5stack install

### ISSUE THREAD

**Issue by tonysoprano187** [justcallmekoko/ESP32Marauder#70]

**Comment by astronomicalunit** [comment]
Hey man i got kidnapped long story ill be home in usa soon. Over encrypted channel ill explain. My best bud had his head cut off stopping a kid sex ring but my shooters ex cia sog para seal 6 or delta etc, made weong turn. Gave em ur decice tho they found me and killed 34 amd let me do the rest with diesel a jacuzzi 6 men and a match amyway hope all is welll we rescued 44 kids under 10 all in dog kennels one guy a cop raping a 4 year old i tortured him over 7 days as a former sof PJ now doctor, navy sarc buddies kept alive and i let his comandente drag him on rocks with truck, bag on head 45 sec 5 off, for 5 days till he died of 77 broken bones 7 vertibre we spiked, cut off nuts and no skin on 78% of body, but heartattack got em. And all the speed doc used so he was awake to feel it and make nerves more sensitive. Anyways hypotethical but if i worked a job thats what my job would have been since 2009.
Opensourcesolutions
Oh yeah fbi hacked my gram but ill have it soon as they had to get told not only can i rendition Americans to mex rxecute with my team, but use tier 1 tools like eod jammers level 4 suv with sting ray, 40mm and go across botder home with one of their scalps but i demanded an apology which ill get cause i do everythime
